# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polymind_pb2 as polymind__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in polymind_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolyMindServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestDocument = channel.unary_unary(
                '/polymind.PolyMindService/IngestDocument',
                request_serializer=polymind__pb2.IngestRequest.SerializeToString,
                response_deserializer=polymind__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.DeleteIndex = channel.unary_unary(
                '/polymind.PolyMindService/DeleteIndex',
                request_serializer=polymind__pb2.DeleteRequest.SerializeToString,
                response_deserializer=polymind__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.QueryDocuments = channel.unary_unary(
                '/polymind.PolyMindService/QueryDocuments',
                request_serializer=polymind__pb2.QueryRequest.SerializeToString,
                response_deserializer=polymind__pb2.QueryResponse.FromString,
                _registered_method=True)


class PolyMindServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolyMindServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=polymind__pb2.IngestRequest.FromString,
                    response_serializer=polymind__pb2.IngestResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=polymind__pb2.DeleteRequest.FromString,
                    response_serializer=polymind__pb2.DeleteResponse.SerializeToString,
            ),
            'QueryDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDocuments,
                    request_deserializer=polymind__pb2.QueryRequest.FromString,
                    response_serializer=polymind__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polymind.PolyMindService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polymind.PolyMindService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolyMindService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymind.PolyMindService/IngestDocument',
            polymind__pb2.IngestRequest.SerializeToString,
            polymind__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymind.PolyMindService/DeleteIndex',
            polymind__pb2.DeleteRequest.SerializeToString,
            polymind__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymind.PolyMindService/QueryDocuments',
            polymind__pb2.QueryRequest.SerializeToString,
            polymind__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
