# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polymind.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polymind.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epolymind.proto\x12\x08polymind\"l\n\rIngestRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\nsize_bytes\x18\x05 \x01(\x03\"0\n\x0eIngestResponse\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1f\n\rDeleteRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\"1\n\x0e\x44\x65leteResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\"V\n\x0cQueryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x14\n\x0c\x64ocument_ids\x18\x02 \x03(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\"9\n\x08\x43itation\x12\x10\n\x08\x64oc_name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\r\n\x05\x63hunk\x18\x03 \x01(\t\"}\n\rQueryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12%\n\tcitations\x18\x03 \x03(\x0b\x32\x12.polymind.Citation\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x15\n\rmessages_json\x18\x05 \x01(\t2\xdb\x01\n\x0fPolyMindService\x12\x43\n\x0eIngestDocument\x12\x17.polymind.IngestRequest\x1a\x18.polymind.IngestResponse\x12@\n\x0b\x44\x65leteIndex\x12\x17.polymind.DeleteRequest\x1a\x18.polymind.DeleteResponse\x12\x41\n\x0eQueryDocuments\x12\x16.polymind.QueryRequest\x1a\x17.polymind.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polymind_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=28
  _globals['_INGESTREQUEST']._serialized_end=136
  _globals['_INGESTRESPONSE']._serialized_start=138
  _globals['_INGESTRESPONSE']._serialized_end=186
  _globals['_DELETEREQUEST']._serialized_start=188
  _globals['_DELETEREQUEST']._serialized_end=219
  _globals['_DELETERESPONSE']._serialized_start=221
  _globals['_DELETERESPONSE']._serialized_end=270
  _globals['_QUERYREQUEST']._serialized_start=272
  _globals['_QUERYREQUEST']._serialized_end=358
  _globals['_CITATION']._serialized_start=360
  _globals['_CITATION']._serialized_end=417
  _globals['_QUERYRESPONSE']._serialized_start=419
  _globals['_QUERYRESPONSE']._serialized_end=544
  _globals['_POLYMINDSERVICE']._serialized_start=547
  _globals['_POLYMINDSERVICE']._serialized_end=766
# @@protoc_insertion_point(module_scope)
