# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traceum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'traceum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtraceum.proto\x12\x07traceum\"\xa1\x01\n\rUpliftRequest\x12\n\n\x02\x66\x30\x18\x01 \x01(\x02\x12\n\n\x02\x66\x31\x18\x02 \x01(\x02\x12\n\n\x02\x66\x32\x18\x03 \x01(\x02\x12\n\n\x02\x66\x33\x18\x04 \x01(\x02\x12\n\n\x02\x66\x34\x18\x05 \x01(\x02\x12\n\n\x02\x66\x35\x18\x06 \x01(\x02\x12\n\n\x02\x66\x36\x18\x07 \x01(\x02\x12\n\n\x02\x66\x37\x18\x08 \x01(\x02\x12\n\n\x02\x66\x38\x18\t \x01(\x02\x12\n\n\x02\x66\x39\x18\n \x01(\x02\x12\x0b\n\x03\x66\x31\x30\x18\x0b \x01(\x02\x12\x0b\n\x03\x66\x31\x31\x18\x0c \x01(\x02\"j\n\x0eUpliftResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08uplift_t\x18\x02 \x01(\x02\x12\x10\n\x08uplift_s\x18\x03 \x01(\x02\x12\x12\n\navg_uplift\x18\x04 \x01(\x02\x12\x0f\n\x07send_ad\x18\x05 \x01(\x08\x32Q\n\rTraceumUplift\x12@\n\rPredictUplift\x12\x16.traceum.UpliftRequest\x1a\x17.traceum.UpliftResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traceum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLIFTREQUEST']._serialized_start=27
  _globals['_UPLIFTREQUEST']._serialized_end=188
  _globals['_UPLIFTRESPONSE']._serialized_start=190
  _globals['_UPLIFTRESPONSE']._serialized_end=296
  _globals['_TRACEUMUPLIFT']._serialized_start=298
  _globals['_TRACEUMUPLIFT']._serialized_end=379
# @@protoc_insertion_point(module_scope)
